# PC-BASIC configuration file.
# Edit this file to change your default settings or add presets.
# Changes to this file will not affect any other users of your computer.
# All lines starting with # are comments and have no effect.
# Thus, to use one of the example options below, you need to remove the # at the start of the line.

[pcbasic]
# Use the [pcbasic] section to specify options you want to be enabled by default.
# See the documentation or run pcbasic -h for a list of available options.
# for example (for version '2.0.7'):
#allow-code-poke=False
#aspect=4,3
#border=5
#caption=PC-BASIC
#cas1=
## choices: 1258, 437, 720, 737, 775, 850, 851, 852, 853, 855, 856, 857, 858, 860, 861, 862, 863, 864, 865, 866, 868, 869, 874, 932, 934, 936, 938, 949, 950, alternativnyj, armscii8a, big5-2003, big5-hkscs, georgian-academy, georgian-ps, iransystem, kamenicky, koi8-r, koi8-ru, koi8-u, mazovia, mik, osnovnoj, ruscii, russup3, russup4ac, russup4na, viscii
#codepage=437
#com1=
#com2=
#config=
#convert=A
#ctrl-c-break=True
#current-device=
#debug=False
#dimensions=
#double=False
#exec=
#extension=
## choices: cga, cgathin, default, mda, olivetti, tandy1, tandy2, vga
font=tandy1
#fullscreen=False
#help=False
#hide-listing=65535
#hide-protected=False
#input=
## choices: , none, cli, text, graphical, ansi, curses, pygame, sdl2
interface=graphical
#keys=
#load=
#logfile=
#lpt1=PRINTER:
#lpt2=
#lpt3=
#max-files=3
#max-memory=65534,4096
#max-reclen=128
## choices: rgb, composite, green, amber, grey, mono
monitor=amber
mount=A:./build
#mouse-clipboard=True
#options=
#output=
#peek=
#prevent-close=False
#quit=False
#reserved-memory=3429
#resume=False
#run=
## choices: smooth, native, crisp
#scaling=smooth
#serial-buffer-size=256
#shell=
#soft-linefeed=False
## choices: true, false, none, beep, portaudio, sdl2, interface
#sound=sdl2
#state=
## choices: advanced, gwbasic, pcjr, tandy
syntax=gwbasic
#term=
#text-encoding=
## choices: 40, 80
#text-width=80
#utf8=False
#version=False
## choices: vga, ega, cga, mda, pcjr, tandy, hercules, olivetti
video=mda
#video-memory=262144
#wait=False


# To add presets, create a section header between brackets and put the 
# options you need below it, like this:
# [your_preset]
# border=0
# 
# You will then be able to load these options with --preset=your_preset.
# If you choose the same name as a system preset, PC-BASIC will use your
# options for that preset and not the system ones. This is not recommended.
